/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
  }
}
