/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminModelManagement: typeof import('./src/components/Admin/AdminModelManagement.vue')['default']
    AdminSystemInfo: typeof import('./src/components/Admin/AdminSystemInfo.vue')['default']
    AdminUserManagement: typeof import('./src/components/Admin/AdminUserManagement.vue')['default']
    AppHeader: typeof import('./src/components/UI/AppHeader.vue')['default']
    ChatContainer: typeof import('./src/components/Chat/ChatContainer.vue')['default']
    ChatHeader: typeof import('./src/components/Chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/Chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/Chat/ChatMessage.vue')['default']
    ChatSidebar: typeof import('./src/components/Chat/ChatSidebar.vue')['default']
    ConfirmationModal: typeof import('./src/components/UI/ConfirmationModal.vue')['default']
    EditableTitle: typeof import('./src/components/Chat/EditableTitle.vue')['default']
    EditUserModal: typeof import('./src/components/Admin/EditUserModal.vue')['default']
    ErrorMessage: typeof import('./src/components/UI/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./src/components/UI/LoadingSpinner.vue')['default']
    ModelSelector: typeof import('./src/components/Chat/ModelSelector.vue')['default']
    OllamaStatusIndicator: typeof import('./src/components/Chat/OllamaStatusIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastContainer: typeof import('./src/components/UI/ToastContainer.vue')['default']
    ToastNotification: typeof import('./src/components/UI/ToastNotification.vue')['default']
    UserSettingsModal: typeof import('./src/components/Admin/UserSettingsModal.vue')['default']
  }
}
