/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ChatContainer: typeof import('./src/components/ChatContainer.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatSidebar: typeof import('./src/components/ChatSidebar.vue')['default']
    EditableTitle: typeof import('./src/components/EditableTitle.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    OllamaStatusIndicator: typeof import('./src/components/OllamaStatusIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
  }
}
