services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rovertchat-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - rovertchat-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rovertchat-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    networks:
      - rovertchat-net

  frontend:
    build:
      context: ./frontend
    container_name: rovertchat-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rovertchat-net

volumes:
  postgres_data:

networks:
  rovertchat-net:
